"""Central configuration: environment, model routing, business rules."""

from __future__ import annotations

import os
from decimal import Decimal
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[2]
load_dotenv(PROJECT_ROOT / ".env")

# --- Qwen Cloud (OpenAI-compatible) ---
QWEN_BASE_URL = os.getenv(
    "QWEN_BASE_URL", "https://dashscope-intl.aliyuncs.com/compatible-mode/v1"
)
QWEN_API_KEY = os.getenv("QWEN_API_KEY", "")

# Model routing: planner does the high-stakes bilingual drafting,
# worker handles extraction/classification, coder handles strict JSON mapping.
PLANNER_MODEL = os.getenv("QWEN_PLANNER_MODEL", "qwen-max")
WORKER_MODEL = os.getenv("QWEN_WORKER_MODEL", "qwen-flash")
CODER_MODEL = os.getenv("QWEN_CODER_MODEL", "qwen3-coder-plus")

# --- Paths ---
DATA_DIR = PROJECT_ROOT / "data"
CATALOG_PATH = DATA_DIR / "catalog.json"
TEMPLATES_DIR = PROJECT_ROOT / "templates"
RUNS_DIR = PROJECT_ROOT / "runs"

# --- Seller identity ---
SELLER = {
    "name_en": "LUQ LABS L.L.C.",
    "name_zh": "LUQ LABS 有限责任公司",
    "jurisdiction_en": "a California limited liability company",
    "jurisdiction_zh": "一家依据美国加利福尼亚州法律设立并存续的有限责任公司",
    "website": "luqlabs.com",
    "email": "sales@luqlabs.com",
}

# --- Business rules ---
QUOTE_VALIDITY_DAYS = 30
WIRE_THRESHOLD_USD = Decimal("50000")  # above this, recommend wire over Stripe
MAX_EXTRA_DISCOUNT_PCT = Decimal("15")  # negotiation floor beyond volume tiers
FALLBACK_USD_CNY = Decimal("7.15")  # offline fallback rate, labeled as indicative
URGENT_DEADLINE_DAYS = 7

# Fixed legal terms (from LUQ LABS' bilingual B2B contract template).
# These are NEVER generated by an LLM — they are the guardrails.
TERMS = {
    "payment_en": (
        "Payment in USD via Stripe invoice; international wire transfer available "
        f"(recommended for orders over USD {WIRE_THRESHOLD_USD:,})."
    ),
    "payment_zh": (
        "以美元通过 Stripe 账单支付;亦可采用国际电汇"
        f"(订单金额超过 {WIRE_THRESHOLD_USD:,} 美元时建议使用电汇)。"
    ),
    "legal_en": (
        "Any resulting agreement is governed by the laws of the State of "
        "California, USA (CISG excluded). Disputes are resolved by arbitration "
        "administered by HKIAC, seated in Hong Kong. The Chinese-language "
        "version of the executed contract is the sole authoritative text; "
        "English text is a courtesy translation."
    ),
    "legal_zh": (
        "由此产生的任何协议均受美国加利福尼亚州法律管辖(排除《联合国国际货物销售"
        "合同公约》适用)。争议提交香港国际仲裁中心(HKIAC)仲裁解决,仲裁地为香港。"
        "正式签署的合同以中文文本为唯一正式文本,英文文本仅为参考译文。"
    ),
    "tax_note_en": (
        "LUQ LABS is a US company and cannot issue Chinese VAT fapiao; a US "
        "invoice and W-8BEN-E form are provided for cross-border tax filing."
    ),
    "tax_note_zh": (
        "LUQ LABS 为美国公司,无法开具中国增值税发票;我方将提供美国形式发票及 "
        "W-8BEN-E 表格,供贵方办理对外支付税务备案。"
    ),
}
